### PR TITLE
fix: Removes stop of UpdateConfig channel loop when 1 item has no network slice

### LINKED ISSUE #134: AMF can't find served TAI when running gnbsim simulation
## Description

The AMF can't find the served TAI when running the gnbsim simulation.

Here are the relevant AMF logs:

```
2023-11-23T00:26:32.467Z [amf] 2023-11-23T00:26:32Z [INFO][AMF][NGAP] [AMF] SCTP Accept from: 10.1.182.39/192.168.251.5:9487
2023-11-23T00:26:32.468Z [amf] 2023-11-23T00:26:32Z [INFO][AMF][NGAP] Create a new NG connection for: 10.1.182.39/192.168.251.5:9487
2023-11-23T00:26:32.469Z [amf] 2023-11-23T00:26:32Z [INFO][AMF][NGAP][10.1.182.39/192.168.251.5:9487] Handle NG Setup request
2023-11-23T00:26:32.469Z [amf] 2023-11-23T00:26:32Z [WARN][AMF][NGAP][10.1.182.39/192.168.251.5:9487] NG-Setup failure: Cannot find Served TAI in AMF
2023-11-23T00:26:32.469Z [amf] 2023-11-23T00:26:32Z [INFO][AMF][NGAP][10.1.182.39/192.168.251.5:9487] Send NG-Setup failure
2023-11-23T00:26:32.471Z [amf] 2023-11-23T00:26:32Z [INFO][AMF][NGAP] Handle SCTP Notification[addr: 10.1.182.39/192.168.251.5:9487]
2023-11-23T00:26:32.471Z [amf] 2023-11-23T00:26:32Z [INFO][AMF][NGAP][10.1.182.39/192.168.251.5:9487] SCTP_SHUTDOWN_EVENT notification, close the connection
2023-11-23T00:26:35.472Z [amf] 2023-11-23T00:26:35Z [INFO][AMF][NGAP][10.1.182.39/192.168.251.5:9487] Remove RAN Context[ID: <PlmnID: {Mcc:208 Mnc:93}, GNbID: 000102>]
2023-11-23T00:26:35.472Z [amf] 2023-11-23T00:26:35Z [INFO][AMF][NGAP] Handle SCTP Notification[addr: <nil>]
2023-11-23T00:26:35.472Z [amf] 2023-11-23T00:26:35Z [WARN][AMF][NGAP] RAN context has been removed[addr: <nil>]
```

Here please note the `NG-Setup failure: Cannot find Served TAI in AMF`

And here are the gnbsim logs:

```
2023-11-23T01:05:12Z [INFO][GNBSIM][App] App Name: GNBSIM
2023-11-23T01:05:12Z [INFO][GNBSIM][App] Setting log level to: trace
2023-11-23T01:05:12Z [TRAC][GNBSIM][Profile][profile1] profile initialized  profile1 , Enable  true
2023-11-23T01:05:12Z [TRAC][GNBSIM][GNodeB][gnb1] Inititializing GNodeB
2023-11-23T01:05:12Z [INFO][GNBSIM][GNodeB][gnb1] GNodeB IP:  GNodeB Port: 9487
2023-11-23T01:05:12Z [INFO][GNBSIM][GNodeB][UserPlaneTransport] User Plane transport listening on: 192.168.251.5:2152
2023-11-23T01:05:12Z [INFO][GNBSIM][GNodeB] Current range selector value: 190
2023-11-23T01:05:12Z [INFO][GNBSIM][GNodeB] Current ID range start: 3187671040 end: 3204448255
2023-11-23T01:05:12Z [TRAC][GNBSIM][GNodeB][ControlPlaneTransport] Connecting to AMF
2023-11-23T01:05:12Z [INFO][GNBSIM][GNodeB][ControlPlaneTransport] Connected to AMF, AMF IP: 10.152.183.32 AMF Port: 38412
2023-11-23T01:05:12Z [TRAC][GNBSIM][GNodeB][gnb1] Performing NG Setup Procedure
2023-11-23T01:05:12Z [TRAC][GNBSIM][GNodeB][gnb1] Sending NG Setup Request
2023-11-23T01:05:12Z [INFO][GNBSIM][GNodeB][ControlPlaneTransport] Wrote 54 bytes
2023-11-23T01:05:12Z [INFO][GNBSIM][GNodeB][ControlPlaneTransport] Read 12 bytes from 10.152.183.32:38412
2023-11-23T01:05:12Z [TRAC][GNBSIM][GNodeB][gnb1] Received NG Setup Response
2023-11-23T01:05:12Z [TRAC][GNBSIM][GNodeB][GnbAmf][] Processing NG Setup Failure
2023-11-23T01:05:12Z [TRAC][GNBSIM][GNodeB][GnbAmf][] Handle NG Setup Failure
2023-11-23T01:05:12Z [TRAC][GNBSIM][GNodeB][GnbAmf][] Decode IE Cause
2023-11-23T01:05:12Z [INFO][GNBSIM][Util][NGAP] Cause Misc[4]
2023-11-23T01:05:12Z [TRAC][GNBSIM][GNodeB][GnbAmf][] Processed NG Setup Failure
2023-11-23T01:05:12Z [INFO][GNBSIM][GNodeB][gnb1] NG Setup Successful: false
2023-11-23T01:05:12Z [ERRO][GNBSIM][GNodeB][gnb1] PerformNgSetup returned: <nil>
2023-11-23T01:05:12Z [ERRO][GNBSIM][GNodeB][gnb1] Failed to initialize GNodeB, err: failed to perform ng setup procedure
2023-11-23T01:05:12Z [ERRO][GNBSIM][App] Failed to initialize gNodeBs: failed to perform ng setup procedure
2023-11-23T01:05:12Z [ERRO][GNBSIM][App] Failed to run GNBSIM: failed to perform ng setup procedure
```

This was not a problem as of commit  https://github.com/omec-project/amf/commit/a4759dbc2da986bbcec0b8edbd9ddbea27a1944d, therefore the problem was likely introduced in one of the following commits:
1. https://github.com/omec-project/amf/commit/3b7558f03d8388b4aac65f27a1d26f93e58e9de7
2. https://github.com/omec-project/amf/commit/418527a62799c9dce7f15ad37d46ed1861a10fd6: Not likely
3. https://github.com/omec-project/amf/commit/e4d4f47b062a3072f0f2a10509d0610f1158cb47
4. https://github.com/omec-project/amf/commit/e22628b90847b8af6dbe0be8543b1e224f6d5ab2
5. https://github.com/omec-project/amf/commit/9cd04c496b032db2861b86f8a95f413cb7e0baf7: Not likely

Note: This suggests that the existing test suite isn't enough to validate regressions.

### PR DESCRIPTION
**Pull request by gruyaume**
## Description

This PR fixes an issue introduced in commit https://github.com/omec-project/amf/commit/3b7558f03d8388b4aac65f27a1d26f93e58e9de7 where the `UpdateConfig` would return early instead of continuously looking for new messages in the channel.

Fixes #134

### CODE REVIEW

**Comment by thakurajayL** [comment]
add to whitelist

File: service/init.go [hunk 1]
```diff
@@ -621,10 +621,6 @@ func (amf *AMF) UpdateConfig(commChannel chan *protos.NetworkSliceResponse) bool
 	for rsp := range commChannel {
 		logger.GrpcLog.Infof("Received updateConfig in the amf app : %v", rsp)
 		var tai []models.Tai
-		var plmnList []*factory.PlmnSupportItem
```
Comment (thakurajayL) [inline service/init.go:624]: what would happen if response is nil. how its going to help?

Comment (gruyaume) [reply service/init.go:624]: This line was simply removed because `plmnList` is not used anywhere. The problem was specifically:

```
if rsp.NetworkSlice == nil {
			return false
		}
```

**Review by ajaythakurintel — APPROVED** [review]

File: service/init.go (hunk 1 above)
Comment (thakurajayL) [reply service/init.go:624]: I added comment at wrong place. I understand plmnlist was not used. My question was about rsp.NetworkSlice.
but I see infinite for loop and program should wait there forever.

**Review by thakurajayL — APPROVED** [review]
